apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-streamlit
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-streamlit
  template:
    metadata:
      labels:
        app: app-streamlit
    spec:
      containers:
      - name: web
        image: jpikovets/streamlit:latest
        env:
          - name: WANDB_API_KEY
            value: "76ee0b1e70d35929fae7f66d69ab36d07abec22a"
---
apiVersion: v1
kind: Service
metadata:
  name: app-streamlit
  namespace: default
spec:
  selector:
    app: app-streamlit
  ports:
  - port: 8080
    protocol: TCP
