apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-streamlit
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-streamlit
  template:
    metadata:
      labels:
        app: app-streamlit
    spec:
      containers:
      - name: web
        image: jpikovets/streamlit:latest
        env:
          - name: WANDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: wandb
                key: WANDB_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: app-streamlit
  namespace: default
spec:
  selector:
    app: app-streamlit
  ports:
  - port: 8080
    protocol: TCP
