apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-web
  template:
    metadata:
      labels:
        app: deployment-web
    spec:
      containers:
      - name: web
        image: jpikovets/web:latest
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-web
  namespace: default
spec:
  selector:
    app: deployment-web
  ports:
  - port: 8080
    protocol: TCP
