name: "[Check] ML Part"

on:
  pull_request:
    paths:
      - "ml/ser/**"
      - "ml/tests/model/**"
      - "ml/tests/code/**"


jobs:
  validate:
    name: Test ml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install -r ml/requirements.txt

      - name: Run model pytest
        run: |
          coverage run  --source=ml -m pytest ml/tests/model

      - name: Run pytest
        run: |
          coverage run --source=ml -m pytest ml/tests/code

      - name: Install `coverage2clover` Python Package
        shell: bash
        run: pip install coverage2clover==4.0.0
      -
        name: Report Coverage
        shell: bash
        run: |
          coverage report -m
          coverage xml
          coverage2clover -i coverage.xml -o clover.xml
      -
        name: Validate and Comment Coverage
        uses: slavcodev/coverage-monitor-action@1.5.0
        with:
          github_token: ${{ secrets.github_token }}
          coverage_path: clover.xml
          threshold_alert: 20
          threshold_warning: 25
          status_context: ${{ github.workflow }} / Verify Unit Tests Coverage
          comment_context: ${{ github.workflow }} / Unit Tests Coverage
