name: "[Check] Web Part"

on:
  pull_request:
    paths:
      - "web/**"


jobs:
  validate:
    name: Test web
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r web/requirements.txt

      - name: Run pytest
        run: |
          PYTHONPATH=web/emotions_recognition_api:ml/ser pytest web/tests
